### ISSUE TITLE
Support PHP 7.4 version

### ISSUE THREAD

**Issue by dardinier** [Coffreo/php-cs-fixer-config#8] opened 2020-06-08 09:21 UTC
Actual version cannot support PHP 7.4+ versions, throwing this error :

```
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.
```

I guess `friendsofphp/php-cs-fixer` dependency need a little update.

**Comment by emri99** [comment] 2020-09-26 14:59
Thanks dear contributor ;))

Cannot reproduce
Just installed on 7.4.10, it works properly.

We could add rules for PHP 7.4, however, for our current use, 7.2 rules are enough.

So I'm closing this issue.

**Closed as completed by emri99** 2020-09-26 14:59 UTC
